dallassoftwaredevelopers/DSDsite

src/app/components/bannerSection/bannerSection.module.css
src/app/components/bannerSection/bannerSection.test.js
src/app/components/bannerSection/bannerSection.tsx
src/app/page.tsx

chore: add banner section (WEB-12)

---

src/app/components/heroSection/heroSection.module.css

fix: Broken Hero Section on Desktop (WEB-17)

---

src/app/components/navbar/navbar.module.css

- Added font weight of 900 to right side navbar items (Community Impact & Contact us)
- Ensured these weights apply in the mobile view as well

fix: Navbar Font weight issue (WEB-19)

---

src/app/components/cardsSection/cards.module.css
src/app/components/cardsSection/cardsSection.tsx

fixed button underline issue: added a  .cardLink CSS property with text-decoration = none to Link component of cardSection.txs.

fix: Button text has underlines (WEB-20)

---

src/app/components/bannerSection/bannerSection.module.css

Added media queries to change banner text to better fit mobile and medium screen sizes.

banner-text-is-not-mobile-friendly-WEB-24-47

---

src/app/components/cardsSection/cards.module.css

fix: card container broken on mobile (WEB-29)

---

CONTRIBUTING.md
package-lock.json
package.json
src/app/components/navbar/navbar.module.css
src/app/components/navbar/navbar.tsx

Changed hamburger menu button in navbar mobile view to a X
Fixed spacing to align X menu button in navbar mobile view
Changed the following for the mobile links in navbar mobile view using Figma as the guidelines:
- font-size: 12px
- font weight: 700
- line height: 14.09px
- text-decoration: none;
- color: #3c3db9;

#45 Richard-Choi/navbarInMobileViewFunctionalityAndStyling WEB-22

---

CONTRIBUTING.md

Step-by-step guide for first-time contributors. Screenshots included

Chore: Details for first contributions (WEB-28)

---

src/app/components/cardsSection/cards.module.css
src/app/components/cardsSection/cardsSection.tsx
src/app/page.tsx

added images to card. passed down the image url and alt as props.

chore: Add images to cards on homepage with borders (WEB-33)

---

src/app/components/bannerSection/bannerSection.module.css
src/app/components/heroSection/heroSection.module.css

Fixed the banner on mobile view

 fix: made by the community banner on mobile not full width (WEB-37) #76

---

src/app/components/layout/layout.tsx

chore: create layout component (WEB-40)

---

src/app/components/footer/footer.module.css
src/app/components/footer/footer.test.js
src/app/components/footer/footer.tsx
src/app/components/footer/footerSocialdata.tsx
src/app/components/socialSection/socialLinks.tsx
src/app/components/socialSection/socialSection.tsx
src/app/layout.tsx

Closes #90  
Preview: 
Desktop
Mobile
I have also modified the Sociallinks.tsx so that the component can be adjusted more easily in the footer and also in future components.

 chore: create a footer according to the Figma design (WEB-42) #90

---

public/assets/video-placeholder.svg
src/app/cohorts/cohorts.module.css
src/app/cohorts/page.tsx
src/app/components/cohortCard/cohortCard.module.css
src/app/components/cohortCard/cohortCard.test.js
src/app/components/cohortCard/cohortCard.tsx

Cohort Page structured out, follows closely with the "the Community" page and reflects the design in the [Figma](https://www.figma.com/design/8cpiqfhzCrzjqK7UOyJKvn/DSD?node-id=706-731&t=d8QiWKILvFkibrzZ-4)
Fulfils #100 
Opens #101
___
Edits cohorts directory under /src to 
- Edit: /cohorts/page.tsx 
- Add: /cohorts/cohorts.module.css
Adds cohortCard directory under /components to be reusable in the list of cohort projects
- Add: /cohortCard/cohortCard.tsx
- Add:  /cohortCard/cohortCard.module.css
- Add:  /cohortCard/cohortCard.test.js
- Links to individual cohort videos
- Links to cohort project repositories (this is optional and will not display clickable element if no link provided)
- Link on OfferingCard component "Get Notified", no target provided

(WEB-51) chore: Add Cohort page

---

src/app/cohorts/cohorts.module.css
src/app/cohorts/page.tsx
src/app/components/cohortCard/cohortCard.module.css
src/app/components/cohortCard/cohortCard.tsx
src/app/components/video/videoFrame.tsx

- Add: Video component that follows YouTube embed specs
- Edit: CohortCard component to take a Video rather than a thumbnail image
- Edit: /cohorts.module.css to properly display the list of Video embeds
**The Video YT link must be an embed link or the video is not displayed correctly**

chore: Add video embeds for Cohorts page (WEB-54)

---

src/app/cohorts/cohorts.module.css
src/app/components/cohortCard/cohortCard.module.css
src/app/components/cohortCard/cohortCard.tsx
src/app/components/video/videoFrame.tsx

* Edit: cohorts/page.tsx Added media queries for tablet/mobile
* Edit: cohorts/page.tsx Changed px measures to rem measures
* Edit: components/cohortCard Added check against useMediaQuery to provide Video component height/width
* Edit: components/video Added props for Height/Width for parent element to control

(WEB-58) chore: Add media queries to Cohorts page

---

src/app/about/about.module.css
src/app/about/page.tsx
src/app/components/footer/footer.module.css
src/app/components/footer/footer.tsx
src/app/globals.css

Global.css will now contain Typography definitions as well as section backgrounds and media queries.
About and Footer components updated to allow global.css changes to take effect.

(WEB-57) CHORE: Add global.css changes/update About and Footer

---

src/app/components/cardsSection/cards.module.css

Full width[1450+]:
width [1040-1450px]:
width [375-1040px]:

chore: Fix layout with cards on home page

---

STYLE_GUIDE.md

Provide an easy to read document for common styles and UI/UX best practices.
This is the initial draft what can be used as a reference to ease development of later components in the site.

(WEB-61) CHORE: Initial Style Guide File

---

src/app/components/navbar/navbar.module.css

chore: create a hover effect for nav buttons

---

src/app/components/heroSection/heroSection.module.css
src/app/components/heroSection/heroSection.tsx

Hie Dennis,
I wanted to let you know that I only made media queries for screen sizes below 850px. I wasn't sure if you also wanted me to increase the size of the video for screen sizes above 850px. Let me know what you think or if there any further changes you would like me to make to the code.
Thanks!

chore: make the video on home responsive #121

---

src/app/cohorts/page.tsx
src/app/community/page.tsx
src/app/components/spinner/spinner.module.css
src/app/components/spinner/spinner.tsx
src/app/hooks/useGlobalState/useGlobalState.tsx

Hello @dgarcia-appdev ,
I have created the load spinner for data fetching.
Please review the code and let me know what your thoughts are.
Thank you as always!

chore: create a load spinner for data fetching (WEB-100) #115

---

README.md

Updated the name in the Contributors to the projects

Updated my name in README.md

---

src/app/community/page.tsx
src/app/components/spinner/spinner.module.css
src/app/components/spinner/spinner.tsx

- Moved Spinner component to individual containers where people data is being fetched on the Community page
- updated the Spinner styles so that it does not take up the full width/height of the screen but only loads in smaller area where used (see screenshot)
- added wrapper div around spinner to add a semi white background so that the purple spinner can be seen on a purple background

chore: rework/add spinner so that it can be used in smaller areas (WEB-124) #127

---

src/app/components/heroSection/heroSection.module.css

chore: increase contrast in mobile view (WEB-126)
